version: '3.5'

services:
  backend:
    build: backend/
    ports:
      - 3005:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=PGPASSWORD
      - DB_NAME=postgres
      - DB_HOST=postgres
    container_name: backend
    depends_on:
      - redis
      - postgres

  frontend:
    build: frontend/
    ports:
      - 3006:5000
    container_name: frontend

  nginx:
    image: nginx
    container_name: nginix
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - ./redis:/data

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PGPASSWORD
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: postgres

volumes:
  postgres:
  nginx:
  redis:
