version: '3.5'

services:

    backend:
        build: backend/
        ports:
            - 3005:8000
        container_name: backend

    frontend:
        build: frontend/
        ports:
            - 3006:5000
        container_name: frontend