version: '3.5'

services:

    backend:
        build: backend/
        ports:
            - 3005:8000
        environment: 
            - REDIS=database
            - REDIS_PORT=6379
        container_name: backend

    frontend:
        build: frontend/
        ports:
            - 3006:5000
        container_name: frontend
    
    database:
        image: redis
        ports: 
            - 6379:6379
        container_name: database